common:
  daemonize: false
  pid_dir: ${PID}
  log_media: ${LOG}
  log_level: info
  working_dir: ${PID}
config_paths:
  config_dir: ${CFG}
  data_dir: ${DATA}
  #simulation_path: /etc/crowdsec/config/simulation.yaml
  #hub_dir: /etc/crowdsec/hub/
  #index_path: /etc/crowdsec/hub/.index.json
crowdsec_service:
  #acquisition_path: ./config/acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  type: sqlite
  db_path: ${DATA}/crowdsec.db
  user: root
  password: crowdsec
  db_name: crowdsec
  host: "172.17.0.2"
  port: 3306
api:
  client:
    credentials_path: ${CFG}/client_secrets.yaml
  server:
    listen_uri: localhost:8080
    online_client: # Crowdsec API
      credentials_path: ${CFG}/lapi-secrets.yaml
prometheus:
  enabled: true
  level: full